version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: concurso_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: concurso_ti

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: concurso_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: node src/server.js

volumes:
  mongo_data: